### PR TITLE
Restructure site for multiple sets of documentation

### PR DESCRIPTION
**Pull request by robin-owen**
This PR restructures content for the Antora site generator to support documentation for multiple aspects of devfiles. No additional content has been written at this time -- the file structure in place for the API and registry documentation is simply a placeholder.

For now, this PR assumes that we will have documentation for the devfile specification, a library/API, and devfile registry.

Note that we also still require a dedicated "start" page with general information and links to other areas of the documentation. This PR does not provide that.

### CODE REVIEW

**Comment by jc-berger** [comment]
I build this PR locally and it all looks good! See the screenshot to view how the new table of contents looks. 
Screen Shot 2021-04-20 at 10 38 17 AM

**Comment by jc-berger** [comment]
@elsony do you have a preference or opinion on the names of the new sections Kevin just made? That is, the following names: 

1. Devfile specification 
2. Devfile library and API
3. Devfile registry 

See the attached screenshot for a visual
Screen Shot 2021-04-20 at 10 38 17 AM

**Comment by jc-berger** [comment]
@slemeur tagging you as well. Please see my above comment. 

Also, new commit, `added placeholder content...` reflects the most recent changes I've made.

**Comment by slemeur** [comment]
Thanks @jc-berger for pinging me on that issue.

I think we need to extract from "Devfile Specification" section some of the end-user aspects. 

This would be a proposal:
**Getting Started**
- What are devfiles?
- How devfiles works?
- Quick Start Guide
- Devfile samples
- Tools using Devfiles

**Using Devfiles**
- Using existing devfiles
- Building a devfile for your project
- Contributing a devfile to the community

**Main Components**
- Devfile Registry
- Devfile Library

** Devfile Specification**
- ...

**Comment by robin-owen** [comment]
Do we want that much placeholder content at this point in time?

The primary purpose of this PR, really, was to move the content "out" one more layer of abstraction so that it will be simpler to add more focused guides in the future as that content becomes available. Adding a new guide at this point essentially entails creating the directory structure and `nav.adoc` for it, then appending the `nav.adoc` into the `nav` key of the `docs/antora.yml` file. That's about as simple as we can get IMHO.

If we start building out the entire structure now, we'll have a documentation site that looks almost empty. It seems to me that it would be relatively simple to "add" guides as we write them, no? That would also allow us a bit more flexibility if we determine that we need to reevaluate that structure as more documentation is worked on.

Thinking about all of this, actually, I wonder if we might do better to remove the placeholder guides for the API/library and registry docs from this PR and simply focus on moving the content out one layer.

(As an aside, I'd also like to go ahead and get this merged in quickly so that @jc-berger can resume working on getting the spec docs in shape. :slightly_smiling_face:)

@slemeur @rkratky Let me know what you think and I'll update this PR accordingly. :slightly_smiling_face:

**Comment by jc-berger** [comment]
Looking at the suggested TOCs, I like Robert's example which blends them together. So taking our existing docs, it'd look something like what I included below. However, I do agree with Kevin that if we go this route now, we'll have a lot of placeholders, so essentially void docs, for our users. That's something we'll want to discuss as we determine what we're pushing now. Maybe placeholders or "empty" docs isn't a concern, but it's something worth brining up. Thanks! 

**Getting Started with Devfiles**

- What are devfiles?

- How devfiles works?

- Devfile properties 

- Quick Start Guide

- Devfile samples

- Tools using Devfiles

**Using Devfiles**

- Using existing devfiles

- Building a devfile for your project

- Contributing a devfile to the community

**Using Devfile Registry**

- ...

- ...

**Using Devfile Library**

- ...

- ...

**Authoring guide**

- ...

**Migration guide**

- ...

**Comment by rkratky** [comment]
> Do we want that much placeholder content at this point in time?

@robin-owen, you misunderstand. I'm not suggesting we actually create all those subsections. I just want to make sure we design the structuring in a way that would allow us to do that in the future. For the time being (until we start adding the new content), we just want to keep the existing content. But it's important to put it in the "right" place, i.e. to name the subdirectory in a way that would play well with the expected future additions.

**Comment by elsony** [comment]
Instead of dividing into using devfiles, using registry, using library, it will be nice if we present those under different persona instead of the technology area, e.g. application developer, architects (stack/sample providers), registry administrator, tools provider, etc., and then put the individual technology-specific info under each persona. If we organize that way, we can also talk about the problems, benefits, values, and use cases for each persona for them to understand how devfile can help them in each case.

**Comment by robin-owen** [comment]
> you misunderstand. I'm not suggesting we actually create all those subsections.

The original Jira issue that this PR addresses specifically mentions creating placeholder content for the proposed structure. :slightly_smiling_face: 

It seems to me that we can create a tracking issue to cover the ToC and how we want to structure that (either on the API GitHub repository or as a docs team Jira issue). For the time being, all we have documented right now is the spec, and each variation of a ToC I've seen so far includes the spec as its own standalone set of documentation. As such, this PR _does_ introduce the structure that we need in order to build content into the desired ToC over time.

I just don't want discussion on this PR to go off onto a tangent that isn't directly related to the changes being introduced here. I'll be removing the placeholder sections for the API and registry docs, as we don't actually have a confirmed location for either of those in the ToC just yet, and it looks like we could definitely use more discussion around how to organize the content.

Please do let me know if there are any other changes which I should introduce to this PR at this point in time or if we're good to merge the contents as-is. Thank you!

**Comment by rkratky** [comment]
> The original Jira issue that this PR addresses specifically mentions creating placeholder content for the proposed structure.

@robin-owen, right, apologies. By that, I only meant the component/guide directories, not the actual section pages etc. I.e. not the fleshing out of the TOC. My bad for the unclear formulation.

> Please do let me know if there are any other changes which I should introduce to this PR at this point in time or if we're good to merge the contents as-is.

No, we're not. The directory structure introduced by this PR needs to reflect the top-level layout of the site. That's what's being discussed here. Merging the PR as it is doesn't help u in any way because we would need to change it again when this discussion is resolved. I understand your desire to merge it ASAP to get a move on, and I myself didn't realize the matter would require so much attention. Again, my bad. But Elson and Stevan have very good points that need to be taken into consideration.

> Instead of dividing into using devfiles, using registry, using library, it will be nice if we present those under different persona instead of the technology area, e.g. application developer, architects (stack/sample providers), registry administrator, tools provider, etc., and then put the individual technology-specific info under each persona.

@elsony, tha's a great point, and you're absolutely right. We should've thought of that. The structure I suggested is heavily feature-based, which is not what we should be after. Basing it on personas allows us to steer it towards user story-based content, which has to be our goal. Shame on me for not giving it enough thought :)

Let's come up with a good use case-based structure.

**Comment by robin-owen** [comment]
In that case, I agree with what @elsony proposed as well.

My point is that before this PR, the documentation focused entirely on the spec as "top level" -- there was no way at all to introduce other guides without substantial work. The changes introduced here make the work trivial to add more guides to the ToC, which I thought was the goal.

If there's another step to be taken (building out the structure ahead-of-time), I don't mind doing that, but I'm not familiar enough with the docs set or what it requires in order to do that. @rkratky, just let me know what structure we'd like to see and I'm happy to implement it.

**Comment by rkratky** [comment]
> The changes introduced here make the work trivial to add more guides to the ToC, which I thought was the goal.

@robin-owen, correct, but we want to get the top-level dir structure right now -- if possible. And as the restructure will involve renaming the current home of the existing content, its name should be decided now, not later (though the other parts can wait, yes).

**Comment by robin-owen** [comment]
Per external discussion with @rkratky and @jc-berger, this PR will continue to focus on the original scope (moving the content "out" one layer, easing the creation of new guides as-needed).

I've created https://github.com/devfile/api/issues/441 (Proposal for new top-level documentation structure) based on the discussion on this PR. We can continue discussing the overall structure/reorganization there.

Thanks, all!

**Comment by rkratky** [comment]
@robin-owen, before we merge as discussed, have you given a thought to redirects? I think we need to consider existing links and bookmarks.

**Comment by rkratky** [comment]
In fact, now that I'm thinking about it... let's take a minute to discuss this more. I apologize for being such a scatterbrain, but it just occurred to me that it might, after all, be better to finalize the proposed new structure, and only then do this move.

**Comment by jc-berger** [comment]
Closing as we have now restructured the TOC.

**Pull request closed without merging**
