### PR TITLE
CI: Add GHA for PR previews through Surge

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description

This PR adds a GHA Action to deploy preview PRs on Surge for easy reviews. 

JIRA ID: https://issues.redhat.com/browse/RHDEVDOCS-3339

### CODE REVIEW

**Review by jc-berger — APPROVED** [review]
/lgtm

**Comment by themr0c** [comment]
I fear it does not  work when the PR originates from a forked repository: it won't have access to the `SURGE_TOKEN` environment variable, because it's a secret available only from the main repository context. Can you proofcheck it?

We had that issue in the che-docs repository, and we solved it as following:

1. A workflow `on pull_request`, running in the context of the fork, does the build and  stores an artifact. See:https://github.com/eclipse/che-docs/blob/master/.github/workflows/build-and-validate-on-pr.yaml
2. A workflow `on workflow_run`, running in the context of the main repository, retrieves the artifact and does the publication using the main repository secret. See:  https://github.com/eclipse/che-docs/blob/master/.github/workflows/publish-netlify.yml

**Comment by themr0c** [comment]
I created a `SURGE_TOKEN` repository token in this repository, using the free account linked to my email address.

**Comment by themr0c** [comment]
Consider adding the  `teardown: 'true'` option.

**Comment by themr0c** [comment]
Failing check, probably because the fork doesn't have access to the `SURGE_TOKEN` secret. See https://github.com/devfile/docs/pull/106#issuecomment-965026196

**Comment by HarshCasper** [comment]
Hi @themr0c 

I have added the Surge Token from my personal account on my fork. I will re-trigger the CI for it to run.

**Comment by HarshCasper** [comment]
Hi @themr0c @rkratky 

The Surge deployed link is available here: devfile-docs-preview-pr-106.surge.sh

The CI fails due to the resources not being available by integration (the GitHub token in my case). In my opinion, it is fit to be merged in the current state and we can check if the Surge deploys the next PR preview.

**Pull request merged**
