### PR TITLE
Generate api reference from json schema

### PR DESCRIPTION
**Pull request by davidfestal**
This PR allows generating the api reference from json schema.

More precisely it:
- reintegrates in the docs repo and docs generation process, the mechanism that until now was run manually to generate the API reference html file from the latest json schema.
- uses an iframe to display the API reference html with its css without interfering with the html files generated by antora. This fixes the broken display that was recently introduced by the addition of the bootstrap css in the main site html.
- simply requires adding the latest json schema as an antora attachment at a given place, and the generation mechanism takes care of the rest.

The resulting site can be tested locally by unzipping the site generated by the GH action run on this PR: 
https://github.com/devfile/docs/suites/1289435469/artifacts/20084246

Notes: 
- this PR will be more easily reviewed commit-per-commit.

### CODE REVIEW

**Comment by l0rd** [comment]
Update the README file with proper commands to test the documentation locally.

**Comment by davidfestal** [comment]
> Update the README file with proper commands to test the documentation locally.

Done @l0rd

**Review by l0rd — APPROVED** [review]
👍

**Comment by mmulholla** [comment]
Can we merge this now?

**Review by elsony — APPROVED** [review]
LGTM

**Pull request merged**
