### PR TITLE
Merge meta.yaml and devfile.yaml

### PR DESCRIPTION
**Pull request by GeekArthur**
Signed-off-by: jingfu wang <jingfu.j.wang@ibm.com>

Fixes https://github.com/devfile/api/issues/172

This PR is used to move fields from meta.yaml to devfile.yaml in terms of documentation.

### CODE REVIEW

**Review by johnmcollier — CHANGES_REQUESTED** [review]
I think these changes need to be made in the github.com/devfile/api repo? As this json file is copied automatically from the generated json spec each time changes are merged into devfile/api

**Comment by GeekArthur** [comment]
> I think these changes need to be made in the github.com/devfile/api repo? As this json file is copied automatically from the generated json spec each time changes are merged into devfile/api

I think the changes for `devfile.json` in this repo is only for documentation, basically what is does is to guide the docs generator to generate the html files so that the new devfile schema can be deployed and displayed on our public website.

**Comment by GeekArthur** [comment]
@johnmcollier https://github.com/devfile/docs/blob/master/generate-api-reference.js#L12 here is the place how this repo uses the `devfile.json` that we change

**Comment by johnmcollier** [comment]
@GeekArthur This CI job https://github.com/devfile/api/blob/master/.github/workflows/ci.yaml#L66 publishes the `devfile.json` to this repository when it's been modified, so any changes in here would get overwritten whenever the devfile api is changed.

**Comment by GeekArthur** [comment]
> @GeekArthur This CI job https://github.com/devfile/api/blob/master/.github/workflows/ci.yaml#L66 publishes the `devfile.json` to this repository whenever the devfile schema has been modified, so any changes in here would get overwritten whenever the job is run.
> 
> If you're adding new fields to the `metadata` field of the devfile spec, wouldn't we need to deliver the changes to https://github.com/devfile/api/blob/1103496bda97425017e4f7fb01e4896ecfa2b5d8/pkg/apis/workspaces/v1alpha2/devworkspace_types.go#L73

Ah, I was missing the CI part in API repo, I am gonna make the changes on API repo, thanks for pointing that out.

**Comment by GeekArthur** [comment]
The changes need to made on API repo as the API repo CI is responsible for syncing the `devfile.json`.

**Pull request closed without merging**
