### PR TITLE
WIP: jcberger_2530_consolidatedevfiledocs

### PR DESCRIPTION
**Pull request by jc-berger**
Fixes [#312 Consolidate devfiles](https://github.com/devfile/api/issues/312#issuecomment-763741070). 

I took the content from [Odo Devfile Properties](https://odo.dev/file-reference/#devfile-properties), removed odo references, and created a new doc for devfiles so our users can work with the yamls for devfiles.  Making a new doc, I followed the naming conventions, but I'm not sure how to add it to the TOC. I'll need help when adding the new doc to our TOC. 

See Jira issue [#2530](https://issues.redhat.com/browse/RHDEVDOCS-2530?filter=-1) for more details.

### CODE REVIEW

**Review by elsony — COMMENTED** [review]
It is not clear to me what is the final goal on how we wanted to present this info based on this PR. This PR only contains a page with the devfile reference content. However, I don't see how this page is being linked back to the main/existing documentation. Also, the information in here is overlapping the information in the stack author's guide. Instead of just moving this page to the repo, should we take a look at the content and merge this with the stack author's guide instead?

**Comment by jc-berger** [comment]
Thanks, Elson. As always, good insight. Tagging, @rkratky, so we can discuss how to streamline this taken taken from odo into our authoring stacks docs.

**Comment by rkratky** [comment]
Ah, apologies. I missed the notification on this one. Looking now.

**Comment by elsony** [comment]
One thing to note is the format on the existing odo page looks clean and concise. That may be the model that is easier to consume than our existing stack authors guide. I am not sure what's the best way to present it but we can consider a hybrid approach where we have a table like the odo one to provide a quick summary and example of each entry. And branch out on the details that is currently not he stack author's guide.

**Comment by jc-berger** [comment]
We don't want to create a new doc as I've done in this PR. Instead, we want to streamline odo's devfile content throughout our devfile docs. Therefore, I opened a new PR, #53, for us to incorporate new changes throughout our docs.

**Comment by jc-berger** [comment]
Closing as PR #53  will track the work.

**Pull request closed without merging**
