### PR TITLE
Modularizing the distribution of files

### PR DESCRIPTION
**Pull request by themr0c**
Pushing the project in the same direction as che-docs.

* Running `gulp` also generates the API reference.
* Name the Antora module _user-guide_ (don't keep default name _ROOT_).
* `antora-playbook.yml`: add edit button, delete old builds, indexify, define AsciiDoc attributes.
* `antora.yml`: contains all metadata.
* Antora `pages` directory contain only metadata and include statement.
* Antora `partials` and `examples` directories contains _Modular Documentation_ topic files: `assembly_*`, `con_*`, `proc_*`, `ref_*`.
* Antora `nav.adoc` uses the pages attributes for titles.
* Compliance of Modular Documentation topics metadata and structure (partials and examples).
* Complete `supplemental-ui` with items borrowed from che-docs.
* Redirections for old pages.

### CODE REVIEW

**Comment by themr0c** [comment]
NB: The `OWNERS` file is missing in the repository, I don't know how we will get through the approval.

**Comment by themr0c** [comment]
This is a preview of the reworked outline:

Screenshot from 2020-11-30 11-18-29

**Comment by themr0c** [comment]
@mmulholl the description in this PR describes most of the good practices I could think of while preparing it. Please ping me for anything left unclear and for a detailed explanation.

**Review by mmulholla — COMMENTED** [review]
Discussed the changes with Fabrice. All looks good to me.

**Review by rkratky — APPROVED** [review]

**Pull request merged**
